from enum import Enum


class PD_MAType(Enum):
    FWMA = "fwma"
    # ALMA = "alma"
    DEMA = "dema"
    EMA = "ema"
    HMA = "hma"
    LINREG = "linreg"
    MIDPOINT = "midpoint"
    PWMA = "pwma"
    RMA = "rma"
    SINWMA = "sinwma"
    SMA = "sma"
    SWMA = "swma"
    SMMA = "smma"
    T3 = "t3"
    TEMA = "tema"
    TRIMA = "trima"
    VIDYA = "vidya"
    WMA = "wma"
    ZLMA = "zlma"
    SSF = "ssf"
    SSF3 = "ssf3"
    

class IndicatorType(Enum):
    FWMA = "Fibonacci Weighted Moving Average (FWMA)"
    DEMA = "Double Exponential Moving Average (DEMA)"
    EMA = "Exponential Moving Average (EMA)"
    HMA = "Hull Moving Average (HMA)"
    LINREG = "Linear Regression (LINREG)"
    MIDPOINT = "Midpoint (MIDPOINT)"
    PWMA = "Parabolic Weighted Moving Average (PWMA)"
    RMA = "Rolling Moving Average (RMA)"
    SINWMA = "Sine Weighted Moving Average (SINWMA)"
    SMA = "Simple Moving Average (SMA)"
    SWMA = "Sine Weighted Moving Average (SWMA)"
    T3 = "Triple Exponential Moving Average (T3)"
    TEMA = "Triple Exponential Moving Average (TEMA)"
    TRIMA = "Triangular Moving Average (TRIMA)"
    VIDYA = "Variable Index Dynamic Average (VIDYA)"
    WMA = "Weighted Moving Average (WMA)"
    ZLMA = "Zero Lag Moving Average (ZLMA)"
    SSF = "Smoothing Step Filter (SSF)"
    SSF3 = "Smoothing Step Filter 3 (SSF3)"

    SMC = "Smart Money Concept"
    IBS = "IBS"
    MACD = "Moving Average Convergence Divergence (MACD)"
    SQEEZE = "SQEEZE"
    AccuDist = "Accumulation/Distribution (ADL)"
    ADX = "Average Directional Index (ADX)"

    AO = "Awesome Oscillator (AO)"
    Aroon = "Aroon"
    ATR = "Average True Range (ATR)"
    BB = "Bollinger Bands (BB)"
    TRENDWITHSL = "Trend With Stop Loss"
    BOP = "Balance of Power (BOP)"
    CCI = "Commodity Channel Index (CCI)"
    ChaikinOsc = "Chaikin Oscillator (ChO)"
    ChandeKrollStop = "Chande Kroll Stop (CKS)"
    CHOP = "Choppiness Index (CHOP)"
    CoppockCurve = "Coppock Curve (CC)"

    DonchianChannels = "Donchian Channel (DC)"
    DPO = "Detrended Price Oscillator (DPO)"

    EMV = "Ease of Movement (EMV)"
    ForceIndex = "Force Index (FI)"

    Ichimoku = "Ichimoku Kinko Hyo"
    KAMA = "Kaufman's Adaptive Moving Average (KAMA)"
    KeltnerChannels = "Keltner Channel (KC)"
    
    KST = "Know Sure Thing (KST)"
    KVO = "Klinger Volume Oscillator (KVO)"
    MassIndex = "Mass Index"
    McGinleyDynamic = "McGinley Dynamic (McD)"
    MeanDev = "Mean Deviation (MDev)"
    PivotsHL = "Pivots High/Low"
    ROC = "Rate of Change (ROC)"
    RSI = "Relative strength index (RSI)"
    MOM = "Momentum"
    ParabolicSAR = "Parabolic SAR"
    SFX = "SFX TOR"

    SMMA = "Smoothed Moving Average (SMMA)"
    OBV = "On-balance Volume (OBV)"
    SOBV = "Smoothed On-balance Volume (SOBV)"
    STC = "Schaff Trend Cycle (STC)"
    StdDev = "StdDev"
    Stoch = "Stochastic Oscillator"
    StochRSI = "Stochastic RSI"
    SuperTrend = "Super Trend"
    EMATrendMetter = "EMA Trend Metter"
    ATRSuperTrend = "ATR Super Trend"
    ZIGZAG = "ZigZag"
    

    TRIX = "TRIX"
    TSI = "True Strength Index (TSI)"
    RVGI = "Relative Vigor Index (RVGI)"
    TTM = "TTM Squeeze"
    UO = "Ultimate Oscillator (UO)"
    VTX = "Vortex Indicator (VTX)"
    VWAP = "Volume Weighted Average Price (VWAP)"
    VWMA = "Volume Weighted Moving Average (VWMA)"
    ZLEMA = "Zero Lag Exponential Moving Average (ZLEMA)"
    SUPERSMOOTH = "Super Smooth Aglorizm"
    CANDLE_PATTERN = "Candle Pattern"
    CUSTOM_CANDLE_PATTERN = "Custom Candle Pattern"
    CHART_PATTERN = "Chart pattern"
    JAPAN_CANDLE = "japan"
    HEIKINASHI_CANDLE = "heikin"
    SMOOTH_JAPAN_CANDLE = "smooth_jp"
    SMOOTH_HEIKINASHI_CANDLE = "smooth_heikin"
    N_SMOOTH_HEIKIN = "n_smooth_heikin"
    N_SMOOTH_JP = "n_smooth_jp"
    VOLUME = "Volume"
    VOLUMEWITHMA = "Volume With MA"
    HISTOGRAM = "Histogram"
    CANDLESTICK = "CandleStick"
    SUB_CHART = "Sub_Chart"
    ATKPRO = "ATKBOT"
    UTBOT = "UTBOT"
    UTBOT_WITH_BBAND = "UTBOT_WITH_BBAND"
    BUY_SELL_WITH_ETM_ST = "EMA Trend Metter Supper Trend"
    ATKBOT_SUPERTREND = "ATKBOTFollowTrend"
    ATKBOT_CCI = "ATKBOTCCI"
    ATKBOT_SUPERTREND_SSCANDLE = "ATKBOTFollowSMCandle"

