import os
import sys

import winloop

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

# ----------------------------------------------------------------------------

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

# ----------------------------------------------------------------------------
import asyncio
import ccxt.pro as ccxt  # noqa: E402
import asyncio

# if hasattr(asyncio, 'WindowsSelectorEventLoopPolicy'):
#     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

winloop.install()
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

# AUTO-TRANSPILE #
async def example():
    binance = ccxt.binance({})
    await binance.load_markets()
    symbol = 'BTC/USDT'
    timeframe = '1m'
    print(binance)
    while True:
        ohlcv = await binance.watch_ohlcv(symbol, timeframe)
        print(ohlcv)

    # await binance.close()

if __name__ == '__main__':
    asyncio.run(example())
