from enum import Enum


class PD_MAType(Enum):
    FWMA = "fwma"
    ALMA = "ALMA"
    DEMA = "dema"
    EMA = "ema"
    HMA = "hma"
    LINREG = "linreg"
    MIDPOINT = "midpoint"
    PWMA = "pwma"
    RMA = "rma"
    SINWMA = "sinwma"
    SMA = "sma"
    SWMA = "swma"
    T3 = "t3"
    TEMA = "tema"
    TRIMA = "trima"
    VIDYA = "vidya"
    WMA = "wma"
    ZLMA = "zlma"
    

class IndicatorType(Enum):
    
    FWMA = "fwma"
    ALMA = "alma"
    DEMA = "dema"
    EMA = "ema"
    HMA = "hma"
    LINREG = "linreg"
    MIDPOINT = "midpoint"
    PWMA = "pwma"
    RMA = "rma"
    SINWMA = "sinwma"
    SMA = "sma"
    SWMA = "swma"
    T3 = "t3"
    TEMA = "tema"
    TRIMA = "trima"
    VIDYA = "vidya"
    WMA = "wma"
    ZLMA = "zlma"
    
    SMC = "Smart Money Concept"
    IBS = "IBS"
    MACD = "Moving Average Convergence Divergence (MACD)"
    AccuDist = "Accumulation/Distribution (ADL)"
    ADX = "Average Directional Index (ADX)"

    AO = "Awesome Oscillator (AO)"
    Aroon = "Aroon"
    ATR = "Average True Range (ATR)"
    BB = "Bollinger Bands (BB)"
    BOP = "Balance of Power (BOP)"
    CCI = "Commodity Channel Index (CCI)"
    ChaikinOsc = "Chaikin Oscillator"
    ChandeKrollStop = "Chande Kroll Stop"
    CHOP = "Choppiness Index (CHOP)"
    CoppockCurve = "Coppock Curve"

    DonchianChannels = "Donchian Channel (DC)"
    DPO = "Detrended Price Oscillator (DPO)"

    EMV = "Ease of Movement (EMV)"
    ForceIndex = "Force Index"

    Ichimoku = "Ichimoku Kinko Hyo"
    KAMA = "KAMA-Kaufman's Adaptive Moving Average"
    KeltnerChannels = "Keltner Channel (KC)"
    KST = "Know Sure Thing (KST)"
    KVO = "Klinger Volume Oscillator (KVO)"
    MassIndex = "Mass Index"
    McGinleyDynamic = "McGinley Dynamic"
    MeanDev = "Mean Deviation"
    PivotsHL = "Pivots High/Low"
    ROC = "Rate of Change (ROC)"
    RSI = "Relative strength index (RSI)"
    ParabolicSAR = "Parabolic SAR"
    SFX = "SFX TOR"

    SMMA = "SMMA-Smoothed Moving Average"
    OBV = "On-balance Volume (OBV)"
    SOBV = "Smoothed On-balance Volume (SOBV)"
    STC = "Schaff Trend Cycle (STC)"
    StdDev = "StdDev"
    Stoch = "Stochastic Oscillator"
    StochRSI = "Stochastic RSI"
    SuperTrend = "Super Trend"

    TRIX = "TRIX"
    TSI = "True Strength Index (TSI)"
    TTM = "TTM Squeeze"
    UO = "Ultimate Oscillator (UO)"
    VTX = "Vortex Indicator (VTX)"
    VWAP = "VWAP"
    VWMA = "VWMA-Volume Weighted Moving Average"
    ZLEMA = "ZLEMA-Zero Lag Exponential Moving Average"
    SUPERSMOOTH = "Super Smooth Aglorizm"
    CANDLE_PATTERN = "Candle Pattern"
    CHART_PATTERN = "Chart pattern"
    JAPAN_CANDLE = "japan"
    HEIKINASHI_CANDLE = "heikin"
    SMOOTH_JAPAN_CANDLE = "smooth_jp"
    SMOOTH_HEIKINASHI_CANDLE = "smooth_heikin"
    N_SMOOTH_HEIKIN = "n_smooth_heikin"
    N_SMOOTH_JP = "n_smooth_jp"
    VOLUME = "Volume"
    HISTOGRAM = "Histogram"
    CANDLESTICK = "CandleStick"
    SUB_CHART = "Sub_Chart"

